<?php

/**
 * Basemail_data
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $type
 * @property string $email_from
 * @property string $name_from
 * @property string $subject
 * @property string $body
 * @property string $phone
 * 
 * @method string    getType()       Returns the current record's "type" value
 * @method string    getEmailFrom()  Returns the current record's "email_from" value
 * @method string    getNameFrom()   Returns the current record's "name_from" value
 * @method string    getSubject()    Returns the current record's "subject" value
 * @method string    getBody()       Returns the current record's "body" value
 * @method string    getPhone()      Returns the current record's "phone" value
 * @method mail_data setType()       Sets the current record's "type" value
 * @method mail_data setEmailFrom()  Sets the current record's "email_from" value
 * @method mail_data setNameFrom()   Sets the current record's "name_from" value
 * @method mail_data setSubject()    Sets the current record's "subject" value
 * @method mail_data setBody()       Sets the current record's "body" value
 * @method mail_data setPhone()      Sets the current record's "phone" value
 * 
 * @package    tnt
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemail_data extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mail_data');
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('email_from', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('name_from', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('subject', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('phone', 'string', 32, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'subject',
              1 => 'body',
             ),
             ));
        $this->actAs($i18n0);
    }
}