<?php

/**
 * Basecarousel_home
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $number_of_slides
 * @property integer $type
 * @property boolean $hidden
 * 
 * @method string        getName()             Returns the current record's "name" value
 * @method integer       getNumberOfSlides()   Returns the current record's "number_of_slides" value
 * @method integer       getType()             Returns the current record's "type" value
 * @method boolean       getHidden()           Returns the current record's "hidden" value
 * @method carousel_home setName()             Sets the current record's "name" value
 * @method carousel_home setNumberOfSlides()   Sets the current record's "number_of_slides" value
 * @method carousel_home setType()             Sets the current record's "type" value
 * @method carousel_home setHidden()           Sets the current record's "hidden" value
 * 
 * @package    madebyrogal
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecarousel_home extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('carousel_home');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 255,
             ));
        $this->hasColumn('number_of_slides', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('type', 'integer', null, array(
             'type' => 'integer',
             'notnull' => false,
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}