<?php

/**
 * Baseproduct_card
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nazwa
 * @property string $opis
 * @property string $opis_2
 * @property boolean $hidden
 * 
 * @method string       getNazwa()  Returns the current record's "nazwa" value
 * @method string       getOpis()   Returns the current record's "opis" value
 * @method string       getOpis2()  Returns the current record's "opis_2" value
 * @method boolean      getHidden() Returns the current record's "hidden" value
 * @method product_card setNazwa()  Sets the current record's "nazwa" value
 * @method product_card setOpis()   Sets the current record's "opis" value
 * @method product_card setOpis2()  Sets the current record's "opis_2" value
 * @method product_card setHidden() Sets the current record's "hidden" value
 * 
 * @package    madebyrogal
 * @subpackage model
 * @author     Tomasz ROGALSKI rogalski.tomaszek@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Baseproduct_card extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_card');
        $this->hasColumn('nazwa', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('opis', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('opis_2', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('hidden', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $sortable0 = new Doctrine_Template_Sortable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'nazwa',
              1 => 'opis',
              2 => 'opis_2',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'nazwa',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'nazwa',
             ),
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($sortable0);
        $this->actAs($i18n0);
    }
}