<?php

/**
 * article_categoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class article_categoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object article_categoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('article_category');
    }
    
    public static function getAllWithArticles(){
        return Doctrine_Query::create()
                ->select('a.id, ac.id AS cat_id, act.id, act.name as cat_name, act.slug AS cat_slug, count(a.id) AS number')
                ->from('article a')
                ->leftJoin('a.category ac')
                ->leftJoin('ac.Translation act')
                ->groupBy('ac.id')
                ->execute();
    }
    
    public static function getCategory($categoryId){
        return Doctrine_Query::create()
                ->from('article_category')
                ->where('id = ?', $categoryId)
                ->andWhere('hidden = ?', 0)
                ->execute()->getFirst();
    }
}