<?php

/**
 * attribute_valueTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class attribute_valueTable extends Doctrine_Table {

  /**
   * Returns an instance of this class.
   *
   * @return object attribute_valueTable
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('attribute_value');
  }

  public static function getProductAttributes($product) {
    $attributes = Doctrine_Query::create()
            ->from('attribute_value')
            ->where('product_id = ?', $product->getId())
            ->execute();

    if ($attributes) {
      $attribteIds = array();
      foreach ($attributes as $attribute) {
        $attribteIds[] = $attribute->getAttributeDefId();
      }
      return $attribteIds;
    } else {
      return false;
    }
  }

  public static function getProductAttributesFrontEnd($product) {
    return Doctrine_Query::create()
                    ->from('attribute_value')
                    ->where('product_id = ?', $product->getId())
                    ->execute();
  }

  public static function createNewAttribute($attributeIdsToAdd, $product) {
    $attributes = attribute_defTable::getAttributeByIds($attributeIdsToAdd);

    if ($attributes) {
      foreach ($attributes as $attribute) {
        $attrValue = new attribute_value();
        $attrValue->setAttributeDefId($attribute->getId())
                ->setAttributeTypeId($attribute->getTypeId())
                ->setProductId($product->getId())
                ->save();
      }

      return true;
    } else {
      return false;
    }
  }

}