<?php

/**
 * carousel_homeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class carousel_homeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object carousel_homeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('carousel_home');
    }
    
    public static function getCarousel($name){
      return Doctrine_QUery::create()
              ->from('carousel_home')
              ->where('name = ?', $name)
              ->andWhere('hidden = 0')
              ->execute()->getFirst();
    }
}