<?php

/**
 * contact_form_1Table
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class contact_form_1Table extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object contact_form_1Table
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('contact_form_1');
    }
}