<?php

/**
 * dictionaryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class dictionaryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object dictionaryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('dictionary');
    }
    
    public static function getAll(){
        $q = Doctrine_Query::create()
                ->from('dictionary')
                ->where('hidden = ?', 0)
                ->execute();
        
        return $q;
    }
}