<?php

/**
 * downloadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class downloadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object downloadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('download');
    }
    
    public static function getAll(){
        $q = Doctrine_Query::create()
                ->from('download')
                ->where('hidden = ?', 0)
                ->execute();
        return $q;
    }
}