<?php

/**
 * faqTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class faqTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object faqTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('faq');
    }
    
    public static function getAllFaq(){
        $q = Doctrine_Query::create()
                ->from('faq')
                ->where('hidden = ?', 0)
                ->execute();
        
        return $q;
    }
}