<?php

/**
 * mail_dataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mail_dataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mail_dataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mail_data');
    }
    
    public static function getMailData($type){
      return Doctrine_Query::create()
              ->from('mail_data')
              ->where('type = ?', $type)
              ->execute()->getFirst();
    }
}