<?php

/**
 * product_cardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class product_cardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object product_cardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('product_card');
    }
    
    public static function getProduct(){
      return Doctrine_Query::create()
              ->from('product_card')
              ->where('hidden = 0')
              ->execute();
    }
}