# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# Root
root:
  url:      /
  param:    { module: main, action: index }

# Home
homepage:
  url:      /
  param:    { module: main, action: index }

# Get File
getFile:
  url:      /pobierz.html
  param:    { module: common, action: getFile }

# Zmiana jezyka
#changeLang:
#  url:      /:slug/change_lang.html
#  class:    sfDoctrineRoute
#  options:  { model: lang, type: object }
#  param:    { module: lang, action: changeLang}

# Strony statyczne
staticPage:
  url:      /:id/:slug.html
  class:    sfDoctrineRoute
  options:  { model: page, type: object }
  param:    { module: page, action: showPage}
  requirements: 
    sf_method: [get,post]

# Naprotechnologia
napotechnologia:
  url:      /naprotechnologia.html  
  param:    { module: naprotech, action: index }

naprotech_doctor:
  url:      /profesorowie-o-naprotechnologi-i-nieplodnosci.html  
  param:    { module: profesors, action: index }
    
# Niepłodność
nieplodnosc:
  url:      /nieplodnosc.html  
  param:    { module: nieplodnosc, action: index }

#FAQ
faq:
  url:      /naprotechnologia-faq.html
  param:    { module: faq, action: index }
  
#Słownik
dictionary:
  url:      /naprotechnologia-slownik.html
  param:    { module: dictionary, action: index }

#Do pobrania
download:
  url:      /naprotechnologia-do-pobrania.html
  param:    { module: download, action: index }

# Przeliczniki - Hormony
conversions_hormons:
  url:      /naprotechnologia-przeliczniki-hormony.html
  param:    { module: przeliczniki, action: hormon }

# Przeliczniki - Indeksy hormonalne
conversions_hormons_complex:
  url:      /naprotechnologia-przeliczniki-indeksy-hormonalne.html
  param:    { module: przeliczniki, action: hormonComplex }

# Przeliczniki - Antropometria
conversions_antropometria:
  url:      /naprotechnologia-przeliczniki-antropometria.html
  param:    { module: przeliczniki, action: antropometria }
  
# Kontakt
contact:
  url:      /kontakt.html
  param:    { module: contact, action: index }
  
# Kontakt
contact_send:
  url:      /wyslij-formularz.html
  param:    { module: contact, action: send }